theme: jekyll-theme-hacker
title: Matt Sampson  <br> I like astrophysics <br> I like mathematics  <br> I like computer <img src="Face.jpeg" align="right" class="inline" height="200">   <img src="Galaxy.jpg" align="right" class="inline" height="200"> 
email: matthew.sampson@connect.qut.edu.au

avatar: <img src="Face.jpeg" height="200"> 
