theme: jekyll-theme-hacker
<> title: Matt Sampson  <br> I like astrophysics <br> I like mathematics  <br> I like computer <img src="Face.jpeg" class="inline" height="200">   <img src="Galaxy.jpg" class="inline" height="200"> <img src="Computer.jpg" class="inline"  height="200"> 
title: <div class="site-branding">
  <div class="site-branding-logo">
    <img src="add/Your/URI/Here" alt="what Is The Image About?" />
  </div>
</div>
<div class="site-branding-text">
  <h1 id="site-title">Site Title</h1>
  <h2 id="site-tagline">Site Tagline</h2>
</div>


email: matthew.sampson@connect.qut.edu.au

avatar: <img src="Face.jpeg" height="200"> 
